
// Client Side State of the store
// Kind of caching...
var places = [];

function getPlaces() {
  return new Promise(resolve => {
    // simple caching mechanism
    if (places.length) {
      resolve(places);
    }
    else {
      setTimeout(() => {
        places = generatePlaces();
        resolve(places);
      }, 500);
    }

  });
}

function getPlaceById(placeId) {
  return getPlaces().then(places => {
    const place = places.find(place => placeId === place.id);
    return place;
  });
}

function deletePlace(place) {
  console.log('Deleting the place', place)
  var idx = places.indexOf(place)
  places.splice(idx, 1);
}

function getNext(place) {
    // select next in a cyclic way
    var idx = places.indexOf(place);
    return (idx < places.length-1)?  
          places[idx+1] : places[0];
}

function savePlace(place) {
  var idx = places.findIndex(currPlace => currPlace.id === place.id);
  //if this is a new place
  if (idx === -1){ 
    //TODO: id should be generated by server
    place.id = places.length + 1; 
    //convert the tags comma seperated string to an array
    place.tags = place.tags.split(',').map(item=>item.trim());
    places.push(place);
  }
  //if this is edit of existing place
  else places.splice(idx, 1, place);
}

// Used to create local data with no AJAX
function generatePlaces() {
  var places = [];
  places.push(generatePlace(1, 'MisterBit',{lat:32.087893,lng:34.803038},['work','study','fun']));
  places.push(generatePlace(2, 'KC Home',{lat:32.069557,lng:34.777067},['center','family','fun']));
  places.push(generatePlace(3, 'KO Home',{lat:32.091208,lng:34.774210},['home','old-north','fun']));
  return places;
}


function generatePlace(id, name, position, tags) {
  return {
    id,
    name,
    tags,
    position
  }
}









// function getProductsFromGenericAPI() {
//   const params = {
//     rows:       10,
//     id:        '{index}',
//     price:     '{number|1000}',
//     title: '{lorem|2}',
//     description: '{lorem|10}',
//     pretty: true
//   }

//   return $.getJSON('http://www.filltext.com', params);

// }

export default {
  getPlaces,
  deletePlace,
  getNext,
  savePlace
}